# config file for the application

Config:
    data_path : '/Data/deeksha/disha/code_p/style_transformer_repl/data/yelp'
    log_dir : 'runs/exp'
    save_path : './save'
    pretrained_embed_path : './embedding/'
    device : "'cuda' if torch.cuda.is_available() else 'cpu'"
    discriminator_method : 'conditional' # 'Multi' or 'Cond'
    load_pretrained_embed : False
    min_freq : 3
    max_length : 100
    embed_size : 256
    d_model : 256
    num_heads : 4
    num_styles : 2
    
    num_classes : "num_styles + 1 if config['discriminator_method'] == 'Multi' else 2"
    num_layers : 8
    batch_size : 4
    lr_style_model : 0.001
    lr_disc_model : 0.001
    L2 : 0
    iter_D : 10
    iter_F : 5
    F_pretrain_iter : 1000
    log_steps : 500
    eval_steps : 500
    learned_pos_embed : True
    dropout : 0.2
    drop_rate_config : '[(1, 0)]'
    temperature_config : '[(1, 0)]'
    self_reconstruction_loss_weight : 0.25
    cyclic_rec_loss_weight : 0.5
    adv_factor : 1

    inp_shuffle_len : 0
    inp_unk_drop_fac : 0
    inp_rand_drop_fac : 0
    inp_drop_prob : 0

    num_style_embeds : 2
    num_enc_layers : 8
    num_dec_layers : 8
    padding_idx : 0
    weight_decay : 0

    load_from : 'None'
    style_model_ckpt : 'save/Jul11003557/ckpts/540_style_model.pth'
    disc_model_ckpt : 'save/Jul11003557/ckpts/540_disc_model.pth'